version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roadmap-frontend
    ports:
      - "5173:5173" # port local:port di container
    stdin_open: true
    tty: true
